import "@/styles/css/styles.css";
import "@/styles/less/top-line.less";
import "@/styles/less/slider-fullscreen.less";
import "@/styles/less/about-us.less";
import "@/styles/less/our-clients.less";
import "@/styles/less/review.less";
import "@/styles/less/our-services.less";
import "@/styles/less/contact.less";
import "@/styles/less/footer.less"
import "@/sliders.js";